# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='type',
            field=models.CharField(default='', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
