# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_reports', '0003_auto_20170804_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.IntegerField(verbose_name='temperature'),
        ),
    ]
