# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_reports', '0004_auto_20170804_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='temperature'),
        ),
    ]
