# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_reports', '0005_auto_20170804_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.CharField(max_length=20, verbose_name='temperature'),
        ),
    ]
